version: '3'
services:
  web:
    build: .
    volumes:
      - ./:/var/www/
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    environment:
            PGPASSWORD: 'secret'
            POSTGRES_DB: 'itigo'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'secret'
    volumes:
      - "./.docker/dbdata:/var/lib/postgresql/data"

  nginx:
    build: ./.docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    depends_on:
      - web
